[package]
name = "mahgit"
version = "0.1.0"
edition = "2024"
description = "Terminal Git interface inspired by Magit"
repository = "https://github.com/andreabergia/mahgit"
homepage = "https://github.com/andreabergia/mahgit"

[lib]
name = "mahgit"
path = "src/lib.rs"

[[bin]]
name = "mahgit"
path = "src/main.rs"

[dependencies]
git2 = { version = "0.19", features = ["vendored-openssl"] }
crossterm = "0.28"
ratatui = "0.29"
thiserror = "1.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
dirs = "6.0.0"
similar = "2.6"
syntect = "5.2"
walkdir = "2.5"

[dev-dependencies]
tempfile = "3.15"
rexpect = "0.5"

[profile.dist]
inherits = "release"
lto = "thin"
