[package]
name = "mahgit"
version = "0.1.0"
edition = "2024"

[lib]
name = "mahgit"
path = "src/lib.rs"

[[bin]]
name = "mahgit"
path = "src/main.rs"

[dependencies]
git2 = "0.19"
crossterm = "0.28"
ratatui = "0.29"
thiserror = "1.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
dirs = "6.0.0"
similar = "2.6"

[dev-dependencies]
tempfile = "3.15"
rexpect = "0.5"
